// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CreateOrder implements CreateOrder operation.
	//
	// Создаёт заказ на космический корабль.
	//
	// POST /api/v1/orders
	CreateOrder(ctx context.Context, req *CreateOrderRequest) (CreateOrderRes, error)
	// GetOrderInfo implements GetOrderInfo operation.
	//
	// Получает информацию по заказу.
	//
	// GET /api/v1/orders/{order_uuid}
	GetOrderInfo(ctx context.Context, params GetOrderInfoParams) (GetOrderInfoRes, error)
	// OrderCancel implements OrderCancel operation.
	//
	// Отменяет заказ.
	//
	// POST /api/v1/orders/{order_uuid}/cancel
	OrderCancel(ctx context.Context, params OrderCancelParams) (OrderCancelRes, error)
	// OrderPay implements OrderPay operation.
	//
	// Order pay.
	//
	// POST /api/v1/orders/{order_uuid}/pay
	OrderPay(ctx context.Context, req *PayOrderRequest, params OrderPayParams) (OrderPayRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
