// Code generated by ogen, DO NOT EDIT.

package order_v1

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// GetOrderInfoParams is parameters of GetOrderInfo operation.
type GetOrderInfoParams struct {
	// ИД заказа.
	OrderUUID uuid.UUID
}

func unpackGetOrderInfoParams(packed middleware.Parameters) (params GetOrderInfoParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeGetOrderInfoParams(args [1]string, argsEscaped bool, r *http.Request) (params GetOrderInfoParams, _ error) {
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// OrderCancelParams is parameters of OrderCancel operation.
type OrderCancelParams struct {
	// ИД заказа.
	OrderUUID uuid.UUID
}

func unpackOrderCancelParams(packed middleware.Parameters) (params OrderCancelParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeOrderCancelParams(args [1]string, argsEscaped bool, r *http.Request) (params OrderCancelParams, _ error) {
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// OrderPayParams is parameters of OrderPay operation.
type OrderPayParams struct {
	// ИД заказа.
	OrderUUID uuid.UUID
}

func unpackOrderPayParams(packed middleware.Parameters) (params OrderPayParams) {
	{
		key := middleware.ParameterKey{
			Name: "order_uuid",
			In:   "path",
		}
		params.OrderUUID = packed[key].(uuid.UUID)
	}
	return params
}

func decodeOrderPayParams(args [1]string, argsEscaped bool, r *http.Request) (params OrderPayParams, _ error) {
	// Decode path: order_uuid.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "order_uuid",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.OrderUUID = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "order_uuid",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
