// Code generated by ogen, DO NOT EDIT.
package order_v1

type CreateOrderRes interface {
	createOrderRes()
}

type GetOrderInfoRes interface {
	getOrderInfoRes()
}

type OrderCancelRes interface {
	orderCancelRes()
}

type OrderPayRes interface {
	orderPayRes()
}
